/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects/check-project-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Check Project Id */
        post: operations["post__check_project_id_projects_check_project_id_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/check-dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Check Dataset */
        post: operations["post__check_dataset_projects_check_dataset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/check-dataset-column": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Dataset Column */
        post: operations["check_dataset_column_projects_check_dataset_column_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get  Projects */
        get: operations["get__projects_projects__get"];
        put?: never;
        /** Create  Project */
        post: operations["create__project_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get  Project */
        get: operations["get__project_projects__project_id__get"];
        /** Update  Project */
        put: operations["update__project_projects__project_id__put"];
        post?: never;
        /** Delete  Project */
        delete: operations["delete__project_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/update-project-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update  Project Id */
        patch: operations["update__project_id_projects__project_id__update_project_id_patch"];
        trace?: never;
    };
    "/enums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get  Enums */
        get: operations["get__enums_enums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/sanity-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Sanity Check */
        post: operations["post__sanity_check_debug_sanity_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/task-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get  Task State */
        get: operations["get__task_state_debug_task_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/result/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get  Result */
        get: operations["get__result_debug_result__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table */
        post: operations["post__get_table_table__project_id___post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column */
        post: operations["post__get_table_column_table__project_id__column_values_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/frequency-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column  Frequency Distribution */
        post: operations["post__get_table_column__frequency_distribution_table__project_id__column_frequency_distribution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column  Counts */
        post: operations["post__get_table_column__counts_table__project_id__column_counts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/geographical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column  Geographical */
        post: operations["post__get_table_column__geographical_table__project_id__column_geographical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/unique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column  Unique */
        post: operations["post__get_table_column__unique_table__project_id__column_unique_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/word-frequencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column  Word Frequencies */
        post: operations["post__get_table_column__word_frequencies_table__project_id__column_word_frequencies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/column/topic-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Get Table Column  Topic Words */
        post: operations["post__get_table_column__topic_words_table__project_id__column_topic_words_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/statistic-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Statistic Test */
        post: operations["post__statistic_test_table__project_id__statistic_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table/{project_id}/compare-group-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post  Compare Group Words */
        post: operations["post__compare_group_words_table__project_id__compare_group_words_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AndTableFilter */
        AndTableFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "and";
            /** Operands */
            operands: (components["schemas"]["_BaseTableFilter"] | components["schemas"]["_BaseCompoundTableFilter"])[];
        };
        /** ApiResult[CheckDatasetResource] */
        ApiResult_CheckDatasetResource_: {
            data: components["schemas"]["CheckDatasetResource"];
            /** Message */
            message: string | null;
        };
        /** ApiResult[InferDatasetColumnResource] */
        ApiResult_InferDatasetColumnResource_: {
            data: components["schemas"]["InferDatasetColumnResource"];
            /** Message */
            message: string | null;
        };
        /** ApiResult[NoneType] */
        ApiResult_NoneType_: {
            /** Data */
            data: null;
            /** Message */
            message: string | null;
        };
        /** ApiResult[ProjectResource] */
        ApiResult_ProjectResource_: {
            data: components["schemas"]["ProjectResource"];
            /** Message */
            message: string | null;
        };
        /** ApiResult[list[ProjectLiteResource]] */
        ApiResult_list_ProjectLiteResource__: {
            /** Data */
            data: components["schemas"]["ProjectLiteResource"][];
            /** Message */
            message: string | null;
        };
        /** CSVDataSource */
        CSVDataSource: {
            /** Path */
            path: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "csv";
            /**
             * Delimiter
             * @default ,
             */
            delimiter: string;
        };
        /** CategoricalSchemaColumn */
        "CategoricalSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "categorical";
        };
        /** CategoricalSchemaColumn */
        "CategoricalSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "categorical";
        };
        /** CheckDatasetColumnSchema */
        CheckDatasetColumnSchema: {
            /** Source */
            source: components["schemas"]["CSVDataSource"] | components["schemas"]["ParquetDataSource"] | components["schemas"]["ExcelDataSource"];
            /** Column */
            column: string;
            dtype: components["schemas"]["SchemaColumnTypeEnum"];
        };
        /** CheckDatasetResource */
        CheckDatasetResource: {
            /** Dataset Columns */
            dataset_columns: string[];
            /** Preview Rows */
            preview_rows: Record<string, never>[];
            /** Total Rows */
            total_rows: number;
            /** Columns */
            columns: components["schemas"]["InferDatasetColumnResource"][];
        };
        /** CheckDatasetSchema */
        CheckDatasetSchema: components["schemas"]["CSVDataSource"] | components["schemas"]["ParquetDataSource"] | components["schemas"]["ExcelDataSource"];
        /** CheckProjectIdSchema */
        CheckProjectIdSchema: {
            /** Project Id */
            project_id: string;
        };
        /** ComparisonGroupWordsSchema */
        ComparisonGroupWordsSchema: {
            /** Groups */
            groups: components["schemas"]["NamedTableFilter"][];
            /** Column */
            column: string;
        };
        /** ComparisonStatisticTestSchema */
        ComparisonStatisticTestSchema: {
            group1: components["schemas"]["NamedTableFilter"];
            group2: components["schemas"]["NamedTableFilter"];
            /** Column */
            column: string;
            statistic_test_preference: components["schemas"]["StatisticTestMethodEnum"];
            effect_size_preference: components["schemas"]["EffectSizeMethodEnum"];
            /** Exclude Overlapping Rows */
            exclude_overlapping_rows: boolean;
        };
        /** Config */
        "Config-Input": {
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Project Id */
            project_id: string;
            /** Source */
            source: components["schemas"]["CSVDataSource"] | components["schemas"]["ParquetDataSource"] | components["schemas"]["ExcelDataSource"];
            data_schema: components["schemas"]["SchemaManager-Input"];
        };
        /** Config */
        "Config-Output": {
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Project Id */
            project_id: string;
            /** Source */
            source: components["schemas"]["CSVDataSource"] | components["schemas"]["ParquetDataSource"] | components["schemas"]["ExcelDataSource"];
            data_schema: components["schemas"]["SchemaManager-Output"];
        };
        /** ContinuousSchemaColumn */
        "ContinuousSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "continuous";
            /** Bins */
            bins?: number[] | null;
            /**
             * Bin Count
             * @default 3
             */
            bin_count: number;
        };
        /** ContinuousSchemaColumn */
        "ContinuousSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "continuous";
            /** Bins */
            bins?: number[] | null;
            /**
             * Bin Count
             * @default 3
             */
            bin_count: number;
        };
        /**
         * DocumentEmbeddingMethodEnum
         * @enum {string}
         */
        DocumentEmbeddingMethodEnum: "doc2vec" | "all-MiniLM-L6-v2" | "lsa";
        /**
         * DocumentPreprocessingMethodEnum
         * @constant
         * @enum {string}
         */
        DocumentPreprocessingMethodEnum: "en_core_web_sm";
        /**
         * EffectSizeMethodEnum
         * @enum {string}
         */
        EffectSizeMethodEnum: "auto" | "mean-difference" | "median-difference" | "cohen-d" | "rank-biserial-correlation" | "cramer-v";
        /** EmptyTableFilter */
        EmptyTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "empty";
        };
        /** EqualToTableFilter */
        EqualToTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "equal_to";
            /** Value */
            value: string | number;
        };
        /** ExcelDataSource */
        ExcelDataSource: {
            /** Path */
            path: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "excel";
            /** Sheet Name */
            sheet_name: string | null;
        };
        /** ExcludesTableFilter */
        ExcludesTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "excludes";
            /** Values */
            values: string[];
        };
        /**
         * GeospatialRoleEnum
         * @enum {string}
         */
        GeospatialRoleEnum: "latitude" | "longitude";
        /** GeospatialSchemaColumn */
        "GeospatialSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "geospatial";
            role: components["schemas"]["GeospatialRoleEnum"];
        };
        /** GeospatialSchemaColumn */
        "GeospatialSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "geospatial";
            role: components["schemas"]["GeospatialRoleEnum"];
        };
        /** GetTableColumnSchema */
        GetTableColumnSchema: {
            /** Column */
            column: string;
            /** Filter */
            filter: (components["schemas"]["AndTableFilter"] | components["schemas"]["OrTableFilter"] | components["schemas"]["NotTableFilter"] | components["schemas"]["EmptyTableFilter"] | components["schemas"]["NotEmptyTableFilter"] | components["schemas"]["EqualToTableFilter"] | components["schemas"]["IsOneOfTableFilter"] | components["schemas"]["GreaterThanTableFilter"] | components["schemas"]["LessThanTableFilter"] | components["schemas"]["GreaterThanOrEqualToTableFilter"] | components["schemas"]["LessThanOrEqualToTableFilter"] | components["schemas"]["HasTextTableFilter"] | components["schemas"]["IncludesTableFilter"] | components["schemas"]["ExcludesTableFilter"] | components["schemas"]["OnlyTableFilter"]) | null;
        };
        /** GetTableGeographicalColumnSchema */
        GetTableGeographicalColumnSchema: {
            /** Filter */
            filter: (components["schemas"]["AndTableFilter"] | components["schemas"]["OrTableFilter"] | components["schemas"]["NotTableFilter"] | components["schemas"]["EmptyTableFilter"] | components["schemas"]["NotEmptyTableFilter"] | components["schemas"]["EqualToTableFilter"] | components["schemas"]["IsOneOfTableFilter"] | components["schemas"]["GreaterThanTableFilter"] | components["schemas"]["LessThanTableFilter"] | components["schemas"]["GreaterThanOrEqualToTableFilter"] | components["schemas"]["LessThanOrEqualToTableFilter"] | components["schemas"]["HasTextTableFilter"] | components["schemas"]["IncludesTableFilter"] | components["schemas"]["ExcludesTableFilter"] | components["schemas"]["OnlyTableFilter"]) | null;
            /** Latitude Column */
            latitude_column: string;
            /** Longitude Column */
            longitude_column: string;
        };
        /** GreaterThanOrEqualToTableFilter */
        GreaterThanOrEqualToTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "greater_than_or_equal_to";
            /** Value */
            value: string | number;
        };
        /** GreaterThanTableFilter */
        GreaterThanTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "greater_than";
            /** Value */
            value: string | number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HasTextTableFilter */
        HasTextTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "has_text";
            /** Value */
            value: string;
        };
        /** IncludesTableFilter */
        IncludesTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "includes";
            /** Values */
            values: string[];
        };
        /** InferDatasetColumnResource */
        InferDatasetColumnResource: {
            /** Name */
            name: string;
            type: components["schemas"]["SchemaColumnTypeEnum"];
            /** Count */
            count: number;
            /** Categories */
            categories: string[] | null;
            descriptive_statistics: components["schemas"]["InferDatasetDescriptiveStatisticsResource"] | null;
        };
        /** InferDatasetDescriptiveStatisticsResource */
        InferDatasetDescriptiveStatisticsResource: {
            /** Count */
            count: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Std */
            std: number;
            /** Min */
            min: number;
            /** Q1 */
            q1: number;
            /** Q3 */
            q3: number;
            /** Max */
            max: number;
            /** Inlier Range */
            inlier_range: [
                number,
                number
            ];
            /** Outlier Count */
            outlier_count: number;
        };
        /** IsOneOfTableFilter */
        IsOneOfTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "is_one_of";
            /** Values */
            values: (string | number)[];
        };
        /** LessThanOrEqualToTableFilter */
        LessThanOrEqualToTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "less_than_or_equal_to";
            /** Value */
            value: string | number;
        };
        /** LessThanTableFilter */
        LessThanTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "less_than";
            /** Value */
            value: string | number;
        };
        /** MultiCategoricalSchemaColumn */
        "MultiCategoricalSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * Delimiter
             * @default ,
             */
            delimiter: string;
            /**
             * Is Json
             * @default true
             */
            is_json: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multi-categorical";
        };
        /** MultiCategoricalSchemaColumn */
        "MultiCategoricalSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Delimiter
             * @default ,
             */
            delimiter: string;
            /**
             * Is Json
             * @default true
             */
            is_json: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multi-categorical";
        };
        /** NamedTableFilter */
        NamedTableFilter: {
            /** Name */
            name: string;
            /** Filter */
            filter: components["schemas"]["AndTableFilter"] | components["schemas"]["OrTableFilter"] | components["schemas"]["NotTableFilter"] | components["schemas"]["EmptyTableFilter"] | components["schemas"]["NotEmptyTableFilter"] | components["schemas"]["EqualToTableFilter"] | components["schemas"]["IsOneOfTableFilter"] | components["schemas"]["GreaterThanTableFilter"] | components["schemas"]["LessThanTableFilter"] | components["schemas"]["GreaterThanOrEqualToTableFilter"] | components["schemas"]["LessThanOrEqualToTableFilter"] | components["schemas"]["HasTextTableFilter"] | components["schemas"]["IncludesTableFilter"] | components["schemas"]["ExcludesTableFilter"] | components["schemas"]["OnlyTableFilter"];
        };
        /** NotEmptyTableFilter */
        NotEmptyTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "not_empty";
        };
        /** NotTableFilter */
        NotTableFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "not";
            /** Operand */
            operand: components["schemas"]["_BaseTableFilter"] | components["schemas"]["_BaseCompoundTableFilter"];
        };
        /** OnlyTableFilter */
        OnlyTableFilter: {
            /** Target */
            target: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "only";
            /** Values */
            values: string[];
        };
        /** OrTableFilter */
        OrTableFilter: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "or";
            /** Operands */
            operands: (components["schemas"]["_BaseTableFilter"] | components["schemas"]["_BaseCompoundTableFilter"])[];
        };
        /** OrderedCategoricalSchemaColumn */
        "OrderedCategoricalSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ordered-categorical";
            /** Category Order */
            category_order?: string[] | null;
        };
        /** OrderedCategoricalSchemaColumn */
        "OrderedCategoricalSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ordered-categorical";
            /** Category Order */
            category_order?: string[] | null;
        };
        /** PaginationParams */
        PaginationParams: {
            /**
             * Page
             * @default 0
             */
            page: number | null;
            /**
             * Limit
             * @default 15
             */
            limit: number | null;
            /** Filter */
            filter?: (components["schemas"]["AndTableFilter"] | components["schemas"]["OrTableFilter"] | components["schemas"]["NotTableFilter"] | components["schemas"]["EmptyTableFilter"] | components["schemas"]["NotEmptyTableFilter"] | components["schemas"]["EqualToTableFilter"] | components["schemas"]["IsOneOfTableFilter"] | components["schemas"]["GreaterThanTableFilter"] | components["schemas"]["LessThanTableFilter"] | components["schemas"]["GreaterThanOrEqualToTableFilter"] | components["schemas"]["LessThanOrEqualToTableFilter"] | components["schemas"]["HasTextTableFilter"] | components["schemas"]["IncludesTableFilter"] | components["schemas"]["ExcludesTableFilter"] | components["schemas"]["OnlyTableFilter"]) | null;
            sort?: components["schemas"]["TableSort"] | null;
        };
        /** ParquetDataSource */
        ParquetDataSource: {
            /** Path */
            path: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "parquet";
        };
        /** ProjectLiteResource */
        ProjectLiteResource: {
            /** Id */
            id: string;
            /** Path */
            path: string;
        };
        /** ProjectResource */
        ProjectResource: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            config: components["schemas"]["Config-Output"];
        };
        /**
         * SchemaColumnTypeEnum
         * @enum {string}
         */
        SchemaColumnTypeEnum: "continuous" | "categorical" | "ordered-categorical" | "multi-categorical" | "temporal" | "textual" | "unique" | "geospatial" | "topic";
        /** SchemaManager */
        "SchemaManager-Input": {
            /** Columns */
            columns: (components["schemas"]["UniqueSchemaColumn-Input"] | components["schemas"]["CategoricalSchemaColumn-Input"] | components["schemas"]["OrderedCategoricalSchemaColumn-Input"] | components["schemas"]["TextualSchemaColumn-Input"] | components["schemas"]["ContinuousSchemaColumn-Input"] | components["schemas"]["TemporalSchemaColumn-Input"] | components["schemas"]["GeospatialSchemaColumn-Input"] | components["schemas"]["MultiCategoricalSchemaColumn-Input"] | components["schemas"]["TopicSchemaColumn-Input"])[];
        };
        /** SchemaManager */
        "SchemaManager-Output": {
            /** Columns */
            columns: (components["schemas"]["UniqueSchemaColumn-Output"] | components["schemas"]["CategoricalSchemaColumn-Output"] | components["schemas"]["OrderedCategoricalSchemaColumn-Output"] | components["schemas"]["TextualSchemaColumn-Output"] | components["schemas"]["ContinuousSchemaColumn-Output"] | components["schemas"]["TemporalSchemaColumn-Output"] | components["schemas"]["GeospatialSchemaColumn-Output"] | components["schemas"]["MultiCategoricalSchemaColumn-Output"] | components["schemas"]["TopicSchemaColumn-Output"])[];
        };
        /**
         * StatisticTestMethodEnum
         * @enum {string}
         */
        StatisticTestMethodEnum: "auto" | "t" | "mann-whitney-u" | "chi-squared";
        /** TableSort */
        TableSort: {
            /** Name */
            name: string;
            /** Asc */
            asc: boolean;
        };
        /** TemporalSchemaColumn */
        "TemporalSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "temporal";
            /** Datetime Format */
            datetime_format: string | null;
        };
        /** TemporalSchemaColumn */
        "TemporalSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "temporal";
            /** Datetime Format */
            datetime_format: string | null;
        };
        /** TextPreprocessingConfig */
        TextPreprocessingConfig: {
            /** @default en_core_web_sm */
            pipeline_type: components["schemas"]["DocumentPreprocessingMethodEnum"];
            /** Ignore Tokens */
            ignore_tokens?: string[];
            /** Stopwords */
            stopwords?: string[];
            /**
             * Remove Email
             * @default true
             */
            remove_email: boolean;
            /**
             * Remove Url
             * @default true
             */
            remove_url: boolean;
            /**
             * Remove Number
             * @default true
             */
            remove_number: boolean;
            /**
             * Min Df
             * @default 5
             */
            min_df: number;
            /**
             * Max Df
             * @default 0.5
             */
            max_df: number;
            /** Max Unique Words */
            max_unique_words?: number | null;
            /**
             * Min Document Length
             * @default 5
             */
            min_document_length: number;
            /**
             * Min Word Length
             * @default 3
             */
            min_word_length: number;
        };
        /** TextualSchemaColumn */
        "TextualSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "textual";
            preprocessing: components["schemas"]["TextPreprocessingConfig"];
            topic_modeling: components["schemas"]["TopicModelingConfig"];
        };
        /** TextualSchemaColumn */
        "TextualSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "textual";
            preprocessing: components["schemas"]["TextPreprocessingConfig"];
            topic_modeling: components["schemas"]["TopicModelingConfig"];
        };
        /** TopicModelingConfig */
        TopicModelingConfig: {
            /**
             * Min Topic Size
             * @default 15
             */
            min_topic_size: number;
            /**
             * Max Topic Size
             * @default 0.2
             */
            max_topic_size: number;
            /**
             * Clustering Conservativeness
             * @default 1
             */
            clustering_conservativeness: number;
            /** Globality Consideration */
            globality_consideration?: number | null;
            /** Max Topics */
            max_topics?: number | null;
            /**
             * N Gram Range
             * @default [
             *       1,
             *       2
             *     ]
             */
            n_gram_range: [
                number,
                number
            ];
            /** @default all-MiniLM-L6-v2 */
            embedding_method: components["schemas"]["DocumentEmbeddingMethodEnum"];
            /**
             * Top N Words
             * @default 50
             */
            top_n_words: number;
            /**
             * No Outliers
             * @default false
             */
            no_outliers: boolean;
            /**
             * Represent Outliers
             * @default false
             */
            represent_outliers: boolean;
        };
        /** TopicSchemaColumn */
        "TopicSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "topic";
        };
        /** TopicSchemaColumn */
        "TopicSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "topic";
        };
        /** UniqueSchemaColumn */
        "UniqueSchemaColumn-Input": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "unique";
        };
        /** UniqueSchemaColumn */
        "UniqueSchemaColumn-Output": {
            /** Name */
            name: string;
            /** Alias */
            alias?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "unique";
        };
        /** UpdateProjectIdSchema */
        UpdateProjectIdSchema: {
            /** Project Id */
            project_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** _BaseCompoundTableFilter */
        _BaseCompoundTableFilter: Record<string, never>;
        /** _BaseTableFilter */
        _BaseTableFilter: {
            /** Target */
            target: string;
            /** Type */
            type: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post__check_project_id_projects_check_project_id_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckProjectIdSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__check_dataset_projects_check_dataset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDatasetSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_CheckDatasetResource_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_dataset_column_projects_check_dataset_column_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDatasetColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_InferDatasetColumnResource_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get__projects_projects__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_list_ProjectLiteResource__"];
                };
            };
        };
    };
    create__project_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Config-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_ProjectResource_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get__project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_ProjectResource_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update__project_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Config-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_ProjectResource_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete__project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update__project_id_projects__project_id__update_project_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectIdSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get__enums_enums_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post__sanity_check_debug_sanity_check_post: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get__task_state_debug_task_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get__result_debug_result__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_table__project_id___post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaginationParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column_table__project_id__column_values_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column__frequency_distribution_table__project_id__column_frequency_distribution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column__counts_table__project_id__column_counts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column__geographical_table__project_id__column_geographical_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableGeographicalColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column__unique_table__project_id__column_unique_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column__word_frequencies_table__project_id__column_word_frequencies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__get_table_column__topic_words_table__project_id__column_topic_words_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetTableColumnSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__statistic_test_table__project_id__statistic_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonStatisticTestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post__compare_group_words_table__project_id__compare_group_words_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonGroupWordsSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
