// This file was auto-generated by scripts/enum-sync.js

export enum AssociationDataTypeEnum {
  Categorical = 'categorical',
  Continuous = 'continuous',
  Temporal = 'temporal',
}

export enum DocumentEmbeddingMethodEnum {
  Doc2Vec = 'doc2vec',
  SBERT = 'sbert',
  TFIDF = 'tfidf',
}

export enum SchemaColumnTypeEnum {
  Continuous = 'continuous',
  Categorical = 'categorical',
  Temporal = 'temporal',
  Textual = 'textual',
  Unique = 'unique',
}

export enum FillNaModeEnum {
  ForwardFill = 'ffill',
  BackwardFill = 'bfill',
  Value = 'value',
  Exclude = 'exclude',
}

export enum DataSourceTypeEnum {
  CSV = 'csv',
  Parquet = 'parquet',
  Excel = 'excel',
}

export enum ProjectTaskStatus {
  Idle = 'idle',
  Pending = 'pending',
  Success = 'success',
  Failed = 'failed',
}

export enum EnumList {
  AssociationDataTypeEnum = 'AssociationDataTypeEnum',
  DocumentEmbeddingMethodEnum = 'DocumentEmbeddingMethodEnum',
  SchemaColumnTypeEnum = 'SchemaColumnTypeEnum',
  FillNaModeEnum = 'FillNaModeEnum',
  DataSourceTypeEnum = 'DataSourceTypeEnum',
  ProjectTaskStatus = 'ProjectTaskStatus',
}
