// This file was auto-generated by scripts/enum-sync.js

export enum SchemaColumnTypeEnum {
  Continuous = 'continuous',
  Categorical = 'categorical',
  Temporal = 'temporal',
  Textual = 'textual',
  Unique = 'unique',
}

export enum DataSourceTypeEnum {
  CSV = 'csv',
  Parquet = 'parquet',
  Excel = 'excel',
}

export enum ProjectTaskStatus {
  Idle = 'idle',
  Pending = 'pending',
  Success = 'success',
  Failed = 'failed',
}

export enum EnumList {
  SchemaColumnTypeEnum = 'SchemaColumnTypeEnum',
  DataSourceTypeEnum = 'DataSourceTypeEnum',
  ProjectTaskStatus = 'ProjectTaskStatus',
}
